
version: "3.1"
services:
  customer_orders_db:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        POSTGRES_DB: customerOrders
   # volumes:
       #- /custom/mount:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    